### ISSUE TITLE
Where can I get this board?

### ISSUE THREAD

**Issue by NigelThorne** [StanislavJochman/LegoSensorAdapter#1]
I see this project is pretty old. Are these boards available I able? If so... where?

**Comment by StanislavJochman** [comment]
Hi this board is not commercially sold but gerbers files are public so you can assemble one yourself. For PCB assembly I can recommend PCBWay. If you want any help hit me up :D.

Best Regards 
Stanislav Jochman

**Comment by Jthawks76** [comment]
Hi, where can you find the files for the board, I am interested in trying to assemble one.

**Comment by StanislavJochman** [comment]
Hi, sorry my repo was private. Here is link: https://github.com/StanislavJochman/Arduino_Lego_Sensor
